### ISSUE TITLE
40265305 - Add a private constructor to hide the implicit public one

### ISSUE THREAD

**Issue by umang232** [HWJFish/OSMDashboard-Winter-2024-SOEN-6431#4]
Whenever there are portions of code that are duplicated and do not depend on the state of their container class, they can be centralized inside a "utility class". A utility class is a class that only has static members, hence it should not be instantiated.
<img width="542" alt="image" src="https://github.com/HWJFish/OSMDashboard-Winter-2024-SOEN-6431/assets/53813466/393654d8-e6f7-4a95-982d-f08b3892835f">

**Comment by HWJFish** [comment]
[https://github.com/HWJFish/OSMDashboard-Winter-2024-SOEN-6431/pull/5#issue-2135216631](url) #5
